- plugins/modules/grafana_dashboard.py
- tests/integration/targets/grafana_dashboard/aliases
- tests/integration/targets/grafana_dashboard/files/dashboard.json
- tests/integration/targets/grafana_dashboard/meta/main.yml
- tests/integration/targets/grafana_dashboard/tasks/dashboard-from-file.yml
- tests/integration/targets/grafana_dashboard/tasks/dashboard-from-id.yml
- tests/integration/targets/grafana_dashboard/tasks/dashboard-from-url.yml
- tests/integration/targets/grafana_dashboard/tasks/delete-dashboard.yml
- tests/integration/targets/grafana_dashboard/tasks/main.yml
Same PR I made on the ansible repo : https://github.com/ansible/ansible/pull/64097
grafana_dashboard.py
The `path` now have a `dashboard_url` alias and accept a HTTP url.
There is also a new `dashboard_id` parameter to import dashboard from grafana.com public dashboard ID.
Example :
- name: Import Grafana dashboard Zabbix
grafana_dashboard:
grafana_url: http://grafana.company.com
grafana_api_key: "{{ grafana_api_key }}"
folder: zabbix
dashboard_id: 6098
- name: Import Grafana dashboard zabbix
grafana_dashboard:
grafana_url: http://grafana.company.com
grafana_api_key: "{{ grafana_api_key }}"
folder: zabbix
dashboard_url: https://grafana.com/api/dashboards/6098/revisions/1/download
Related Issues / pulls :
https://github.com/ansible/ansible/issues/52636 …
> Import dashboard from url or grafana.com public ID + integration tests

- plugins/modules/grafana_dashboard.py
grafana_dashboard: state has a default, therefore we don't require end-users authors to explicitly set it in the playbooks
> grafana_dashboard: state isn't required as we have a default

- plugins/modules/grafana_datasource.py
Grafana datasource module : 
`ds_type` parameter was marqued required in documentation, but not in specs.
grafana-datasources.py
Related : https://github.com/gundalow-collections/grafana/pull/15
> ds_type is required in spec

- .github/workflows/ansible-test.yml
By the time Ansible 2.10 has been released ansible/ansible will have been reduced to include only a very [small set of plugins](https://github.com/ansible-community/collection_migration/tree/master/scenarios/minimal) known as `ansible-minimal`
We should start running tests against this reduced set to ensure we don't have dependencies on anything else.
> CI to use ansible-minimal

- plugins/callback/grafana_annotations.py
Tags cannot be customized, add hostname to the tags for the annotations so the annotations can be filtered by hosts.
I added hostname to the tags but I'm open to another solution to be more generic.
grafana_annotations
I have one prometheus with one grafana to centralize my logs. I can filter my data based on my host but I cannot filter my annotations. Adding this feature will allow me to filter my host and annotations.
> feature(grafana_annotations): add hostname to tags

- .github/workflows/ansible-test.yml
If we use the "push" keyword, the CI won't be triggered by Pull Requests
made by people who forked the repository. So contributions won't go
through our awesome CI.
I made this change based on : https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows#pull-request-event-pull_request
> Change the GitHub Actions trigger to pull request

- plugins/modules/grafana_team.py
Fix  `ERROR: Found 1 validate-modules issue(s) which need to be resolved:
ERROR: plugins/modules/grafana_team.py:0:0: parameter-list-no-elements: Argument 'members' in argument_spec defines type as list but elements is not defined`
> grafana_team member elements is str

- plugins/modules/grafana_plugin.py
Fixes #45 
grafana_plugin
See issue #67042 
Running with this fix reports on first installation:
```
changed: [****] => {
"changed": true,
"invocation": {
"module_args": {
"grafana_plugin_url": "/tmp/grafana-grafana-polystat-panel-v1.1.0-0-ga6cdad4.zip",
"grafana_plugins_dir": null,
"grafana_repo": null,
"name": "grafana-polystat-panel",
"state": "present",
"version": null
}
},
"msg": "Grafana plugin grafana-polystat-panel installed : /sbin/grafana-cli --pluginUrl /tmp/grafana-grafana-polystat-panel-v1.1.0-0-ga6cdad4.zip plugins install grafana-polysta
t-panel",
"version": ""
}
```
and on rerun:
```
ok: [****] => {
"changed": false,
"invocation": {
"module_args": {
"grafana_plugin_url": "/tmp/grafana-grafana-polystat-panel-v1.1.0-0-ga6cdad4.zip", …
```
> grafana_plugin fix error on missing plugin_version

- plugins/modules/grafana_dashboard.py
- plugins/modules/grafana_user.py
- tests/integration/targets/grafana_dashboard/tasks/dashboard-from-file.yml
- tests/integration/targets/grafana_dashboard/tasks/dashboard-from-id.yml
- tests/integration/targets/grafana_dashboard/tasks/dashboard-from-url.yml
- tests/sanity/ignore-2.10.txt
Changes were made on `grafana_dashboard` after a bugfix. Modules paramters
now have forbidden keywords like `message`.
See https://github.com/ansible/ansible/pull/60051
> Applying changes made in ansible/ansible

- .github/workflows/ansible-test.yml
- README.md
Grafana v7 was released, let's see what is now broken in the collection 🥳
> Test Grafana 7.x

- plugins/modules/grafana_datasource.py
- tests/sanity/ignore-2.11.txt
You are able to select es version 6.0+ and 7.0+ in the grafana GUI.
This change will support this via the ansible module.
> support elasticsearch version 6.0+, 7.0+

- plugins/modules/grafana_dashboard.py
- plugins/modules/grafana_datasource.py
- plugins/modules/grafana_folder.py
- plugins/modules/grafana_team.py
- plugins/modules/grafana_user.py
- tests/integration/targets/grafana_datasource/tasks/elastic.yml
fixes #106 
fixes #107
fixes #109 
fixes #110 
**IMPORTANT: this PR might change previous behaviour!** because:
- As until now (#107) once a datasource where created or updated with any secureJsonData further changes wouldn't be updated and reporting changed=false. With this PR each run will change the fields, which should be the expected result anyways!
- Ad #110: Users don't HAVE to change anything as from now on password isn't save to secureJsonData.password but just password. Runs won't report change=True like above. BUT: they have to switch to secure_password if they want to use encrypted passwords.
> adding additional_secure_json_data

- plugins/modules/grafana_datasource.py
Removing `secure_password` before v1.0.0
Remove the option in favor of additional_secure_json_data
> remove secure password

- plugins/callback/grafana_annotations.py
- plugins/lookup/grafana_dashboard.py
According to https://github.com/ansible/ansible/issues/71795, `<plugin_type>:` should be replaced by `name:` in the plugin docs. Also according to https://github.com/ansible/ansible/issues/71798, `callback_type` should be renamed to `type`. Finally, imports should be below the docs (but before anything else), as will be reported by ansible/ansible#71734.
I marked this as [WIP] since it should wait until ansible/ansible#71734 is finalized.
collection
> [WIP] Fix plugin sanity

- plugins/callback/grafana_annotations.py
Respect `ignore_errors: True` task option in `grafana_annotations.py` and don't send an annotation on these tasks.
Also `self.errors += 1` when the error is not ignored otherwise the playbook is marked as failing in `v2_runner_on_failed` and the execution is marked as red in Grafana.
```paste below
```
> respect ignore_errors in grafana_annotations.py

- .github/workflows/ansible-test.yml
Add rust and cargo in the install deps to allow cryptography installation to work again.
See related drama: https://github.com/pyca/cryptography/issues/5771
> Add rust and cargo in alpine deps to allow ansible install to work again

- plugins/module_utils/base.py
- plugins/modules/grafana_dashboard.py
- plugins/modules/grafana_datasource.py
- plugins/modules/grafana_folder.py
- plugins/modules/grafana_notification_channel.py
- plugins/modules/grafana_team.py
- plugins/modules/grafana_user.py
Remove trailing slashes from the Grafana URL to avoid double slashes when concatenating the URI
Closes: #135
> Remove trailing slash from provided grafana url

- plugins/modules/grafana_datasource.py
- tests/integration/targets/grafana_datasource/tasks/elastic.yml
- tests/integration/targets/grafana_datasource/tasks/influx.yml
Fixes https://github.com/ansible-collections/community.grafana/issues/155
As described in https://github.com/ansible-collections/community.grafana/issues/155 the option `With CA Cert` will not be enabled if only the parameter `tls_ca_cert` is set.
grafana_datasource.py
I reproduced the issue https://github.com/ansible-collections/community.grafana/issues/155 with prometheus datasource. 
1. Create Root CA cert + key
2. Self sign Root CA
3. Create CSR for datasource Domain
4. Sign CSR with Root CA
5. Execute playbook with Root CA as multi line string var
```yaml
- name: Create Loki datasource
community.grafana.grafana_datasource:
name: "Prom"
grafana_url: "https://localhost:3000"
ds_type: "prometheus"
ds_url: "https://your.domain"
basic_auth_user: "..." …
```
> Fix 155: Enable tlsAuthWithCACert when using CA Cert

- plugins/modules/grafana_dashboard.py
This was beforehand looking for a 'commit_message', when it should be looking for a 'message'
- Bugfix Pull Request #153 
Before:
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'commit_message'
failed: [instance] (item={'folder': 'third_party/monitoring', 'id': 3662}) => {"ansible_loop_var": "item", "changed": false, "item": {"folder": "third_party/monitoring", "id": 3662}, "module_stderr": "Traceback (most recent call last):\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1619283964.3088856-17152-243989361125190/AnsiballZ_grafana_dashboard.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1619283964.3088856-17152-243989361125190/AnsiballZ_grafana_dashboard.p …
```
> Fix extraction of the error message on update of a dashboard

- changelogs/fragments/1.2.2.yml
- plugins/modules/grafana_dashboard.py
- tests/integration/targets/grafana_dashboard/tasks/dashboard-folder-destination.yml
- tests/integration/targets/grafana_dashboard/tasks/main.yml
The `grafana_dashboard` module currently silently fails (that is, succeeds) to add a new dashboard if the directory in which the dashboard should be put doesn't exist.
I believe this is unintuitive and at least lost me quite some time trying to understanding why I did not see my dashboard when everything was fine.
In order to reproduce:
- Setup a grafana instance
- Add a new dashboard to it, to a directory that does not exists
- Expected: it fails? Or creates the folder?
- Currently: it succeeds but the dashboard is not uploaded
I have made directly a PR as I think this is a bug? Let me know if you want an issue to discuss this first :)
Also, if you accept that change I was not sure how to add a changelog entry, and would appreciate guidance.
Thanks …
> dashboard: Fail if the target directory does not exist

- changelogs/fragments/1.2.2.yml
- plugins/modules/grafana_team.py
grafana_team: unable to use spaces or other utf-8 chars in name/title
Same PR like for grafana_folder #79 
Fix issue #164 
- Bug Report
grafana_team
```paste below
ansible 2.9.15
config file = /mnt/c/DeveloperArea/Telia/moncap-repo/ansible.cfg
configured module search path = ['/home/myuser/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /usr/lib/python3.9/site-packages/ansible
executable location = /usr/bin/ansible
python version = 3.9.0 (default, Oct  6 2020, 00:00:00) [GCC 10.2.1 20200826 (Red Hat 10.2.1-3)]
collection:
community.grafana 1.2.1
```
```paste below
```
Ubuntu 18.04.3 LTS
Procedure described in : #164
Teams should be created.
Error, because not URL quote for the get_folder API query.
```paste below
msg": "Grafana Folders API …
```
> grafana_team: unable to use spaces or other utf-8 chars in name/title

- changelogs/fragments/158-grafana_dashboard-lookup-api-key.yml
- plugins/lookup/grafana_dashboard.py
The code assumed a static amount of base64 padding, which is not always correct. The simplest way to fix this is to parse the arguments correctly and trust the user to pass the correct API key.
(Even better would be to use plugin options and deprecate the k=v string parsing, but that's more work than I'm prepared to do at the moment.) 
grafana_dashboard lookup
Before:
```
ec2-user@pandora ~ $ ansible localhost -m debug -a "msg={{ q('grafana_dashboard', 'grafana_url=https://graphs.x.mail.umich.edu grafana_api_key=eyJrIjoiajZwQUNZRlVJM2FuTjRmM0hlUFpJU2xTUFFRV2RTenYiLCJuIjoidGVzdDEiLCJpZCI6MX0=') }}"
localhost | FAILED! => {
"msg": "An unhandled exception occurred while running the lookup plugin 'grafana_dashboard'. Error was a <class 'ansible.errors.AnsibleError'>, …
```
> grafana_dashboard lookup: fix passing API key

- plugins/modules/grafana_datasource.py
- tests/integration/targets/grafana_datasource/tasks/main.yml
- tests/integration/targets/grafana_datasource/tasks/redis.yml
A simple insertion of `redis-datasource` as accepted value for `ds_type`.
`community.grafana.grafana_datasource`
Both authenticated and non-authenticated Redis instances work that way (already supported from module arguments `database` and `password`) only thing I haven't found yet is how to change type from Standalone to e.g. Sentinel, Cluster.
Example task for creating a Redis datasource:
```yaml
- name: Create grafana redis datasource
community.grafana.grafana_datasource:
name: "redis-local-test"
grafana_url: "{{ grafana.url }}"
grafana_api_key: "{{ grafana.api_key }}"
ds_type: "redis-datasource"
ds_url: "redis://redis:6379"
```
A task like the one above will output the following: 
```json
changed: [grafana-host] => {
"changed": true,
"datasource": {
"access": …
```
> add redis-datasource

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/1.2.3.yml
- galaxy.yml
- plugins/modules/grafana_folder.py
- plugins/modules/grafana_team.py
- tests/integration/targets/grafana_dashboard/defaults/main.yml
- tests/integration/targets/grafana_datasource/defaults/main.yml
- tests/integration/targets/grafana_folder/defaults/main.yml
- tests/integration/targets/grafana_notification_channel/defaults/main.yml
- tests/integration/targets/grafana_team/defaults/main.yml
- tests/integration/targets/grafana_team/tasks/create_user.yml
- tests/integration/targets/grafana_user/defaults/main.yml
- tests/integration/targets/grafana_user/tasks/main.yml
Support different grafana url format that could finish with with a slash or not depending on user habit.
Fixes #183"
plugins/modules/grafana_datasource.py
plugins/modules/grafana_folder.py
plugins/modules/grafana_team.py
plugins/modules/grafana_user.py
N/A
> fix: support trailing slash in grafana_url

- CHANGELOG.rst
- README.md
- galaxy.yml
- plugins/modules/grafana_datasource.py
Fixes #205 
Allows setting the auth type to `default`
This allows you to fall back to using the `instance profile` of the EC2 Instance you are running on.
> Datasource - Add 'AWS SDK Default' as an auth type

- CHANGELOG.rst
- plugins/modules/grafana_notification_channel.py
- tests/integration/targets/grafana_notification_channel/tasks/threema.yml
Fixes #208
grafana_notification_channel
- Fixed some typos that caused options for Threema notification channel to be ignored
- Updated tests accordingly
- Added a missing line break that caused a rstcheck error (sanity test)
> Bugfix - Threema notification channels

- README.md
- plugins/modules/grafana_datasource.py
Fixes #204 
- See [my comment](https://github.com/ansible-collections/community.grafana/issues/204#issuecomment-1047130250)
- Use of encrypted passwords for datasources is possible since Grafana v6.2.0. If accepted, this changes will make grafana_datasource module not compatible with Grafana v6.1.6 (released in Apr. 2019) and ealier.
> Use encrypted passwords for datasources

- .github/workflows/ansible-test.yml
- .github/workflows/rebase.yml
- README.md
- plugins/modules/grafana_user.py
Update and improve the Github workflows:
- upgrade versions of  `actions/checkout`, `actions/setup-python` and `codecov/codecov-action` (codecov-action@v1 is [deprecated](https://github.com/codecov/codecov-action/blob/master/CHANGELOG.md#200))
- add coverage for sanity and integration tests
- fix an error reported by sanity tests (line too long)
- fix the codecov badge URL (currently links to the old repository: `ansible-collections/grafana`)
- run workflow on push to main branch (so that the coverage is generated and displayed for the default branch in codecov)
@gundalow @rrey @seuf it seems that codecov overview displays coverage for the `master` branch (that no longer exists) and not `main`. Can one of you look at the [codecov …
> test: update GitHub workflows

- .github/workflows/ansible-test.yml
- codecov.yml
Add configuration for codecov file viewer.
- Set `fixes` in `codecov.yml` so that codecov can get the source code. Fixes this [issue](https://app.codecov.io/gh/ansible-collections/community.grafana/blob/911180307966b81194b98cd5688f67a7bb5bd38c/ansible_collections/community/grafana/plugins/modules/grafana_dashboard.py) : "There was a problem getting the source code from your provider. Unable to show line by line coverage.".  
- Added flags to differentiate the type of tests.
> ci: add configuration for codecov file viewer

- README.md
- changelogs/fragments/136_add_grafana_action_groups.yml
- meta/runtime.yml
- plugins/callback/grafana_annotations.py
- plugins/modules/grafana_dashboard.py
Add `grafana` action group to support module group defaults.
Fixes #136 
Works with [ansible-core 2.12.0 and later](https://github.com/ansible/ansible/pull/74039) ([doc](https://github.com/ansible/ansible/blob/v2.12.3/docs/docsite/rst/user_guide/playbooks_module_defaults.rst#module-defaults-groups)):
```yml
- hosts: 'localhost'
collections:
- community.grafana
module_defaults:
group/community.grafana.grafana:
grafana_url: "http://localhost:3000"
grafana_user: "admin"
grafana_password: "admin"
tasks:
- name: add datasource
grafana_datasource:
name: "datasource-prometheus"
ds_type: "prometheus"
ds_url: "http://prometheus:9090"
- name: add dashboard
grafana_dashboard:
commit_message: "Updated by ansible"
dashboard_id: "6098"
dashboard_revision: "1"
```
> feat: add support for module group defaults

- changelogs/fragments/170_remove_requirement_ds_type_ds_url.yml
- plugins/modules/grafana_datasource.py
- tests/integration/targets/grafana_datasource/tasks/cloudwatch.yml
- tests/integration/targets/grafana_datasource/tasks/elastic.yml
- tests/integration/targets/grafana_datasource/tasks/errors.yml
- tests/integration/targets/grafana_datasource/tasks/influx.yml
- tests/integration/targets/grafana_datasource/tasks/loki.yml
- tests/integration/targets/grafana_datasource/tasks/main.yml
- tests/integration/targets/grafana_datasource/tasks/postgres.yml
- tests/integration/targets/grafana_datasource/tasks/redis.yml
- tests/integration/targets/grafana_datasource/tasks/thruk.yml
- tests/integration/targets/grafana_datasource/tasks/zabbix.yml
Fixes #170.
Require `ds_type` and `ds_url` only when creating or updating a datasource.
- Added an integration test for missing parameters (`ds_type` and `ds_url`) when creating or updating a datasource
- Removed useless parameters when deleting datasources in integration tests ([only the name is used for deleting](https://github.com/ansible-collections/community.grafana/blob/911180307966b81194b98cd5688f67a7bb5bd38c/plugins/modules/grafana_datasource.py#L645))
> fix(grafana_datasource): remove requirement for `ds_type` and `ds_url`

- changelogs/fragments/239_keyerror_grafana_url.yml
- plugins/modules/grafana_dashboard.py
- plugins/modules/grafana_notification_channel.py
Fixes #239.
Use `url` (option's name) instead of `grafana_url` (option's alias) when accessing modules params in `grafana_dashboard` and `grafana_notification_channel`.  
grafana_notification_channel
Module params values should be accessed by using the option's name and not an alias.  
```
TASK [Create dashboard] *************************************************************************************************************************************************************************************
changed: [localhost]
TASK [Create notification channel] **************************************************************************************************************************************************************************
changed: [localhost]
```
> Fix KeyError fatal error when using `url` option instead of `grafana_url`

- .github/workflows/fragment.yml
- README.md
- changelogs/fragments/186_check_fragments.yml
- hacking/NEED_FRAGMENT
- hacking/check_fragment.sh
- tests/sanity/ignore-2.10.txt
- tests/sanity/ignore-2.11.txt
- tests/sanity/ignore-2.12.txt
- tests/sanity/ignore-2.13.txt
- tests/sanity/ignore-2.14.txt
- tests/sanity/ignore-2.9.txt
Add a workflow that will check that a changelog fragment is present in the PR.
If not, a review will be posted on the PR asking for the change. If file is present, the PR will be approved by the action.
The CI will still require a code owner review and merge from maintainer.
> Add a workflow looking for changelog fragments

- .github/workflows/ansible-test.yml
- tests/integration/targets/grafana_datasource/tasks/azure.yml
- tests/integration/targets/grafana_datasource/tasks/cloudwatch.yml
- tests/integration/targets/grafana_datasource/tasks/elastic.yml
- tests/integration/targets/grafana_datasource/tasks/influx.yml
- tests/integration/targets/grafana_datasource/tasks/issues.yml
- tests/integration/targets/grafana_datasource/tasks/loki.yml
- tests/integration/targets/grafana_datasource/tasks/thruk.yml
- tests/integration/targets/grafana_datasource/tasks/zabbix.yml
- tests/integration/targets/grafana_team/tasks/main.yml
Support Grafana 9 in integration tests.
Notes specific to behavior observed in Grafana 9.0.0:
* For datasources, Grafana does not return the `password` field anymore.
* For teams, Grafana now automatically adds the user creating the team
as a member. Also, Grafana does not allow removing the last admin user
from a team.
> test: Support Grafana 9 in integration tests

- .github/workflows/fragment.yml
- hacking/check_fragment.sh
Github actions permissions from forks will not allow the github token
to perform comments of approves on the PR, breaking the initial idea.
Updating the workflow to simply fail if the changelog fragment is
present and display the error message in the workflow logs.
> fix(changelog-fragment): do not comment or approve from actions

- CHANGELOG.rst
- changelogs/changelog.yaml
- galaxy.yml
v1.5.0
======
Minor Changes
-------------
- community.grafana.grafana_datasource supports grafana-azure-monitor-datasource.
Bugfixes
--------
- Fix a bug that causes a fatal error when using `url` parameter in `grafana_dashboard` and `grafana_notification_channel` modules.
- Fix a bug that causes an update error when using the `grafana_datasource` module on Grafana >=9.0.0 (https://github.com/ansible-collections/community.grafana/issues/248).
> build(release): 1.5.0

- changelogs/fragments/265-url-encode-user.yml
- plugins/modules/grafana_team.py
- plugins/modules/grafana_user.py
Fixes https://github.com/ansible-collections/community.grafana/issues/264
grafana_team
Currently searching for users with + in the email address will fail, as the character won't be properly encoded `/api/users/lookup?loginOrEmail=myaccount+grafana@gmail.com`
> url encode user email/login

- changelogs/fragments/265-url-encode-user.yml
- tests/integration/targets/grafana_team/tasks/create_user.yml
- tests/integration/targets/grafana_team/tasks/main.yml
- tests/integration/targets/grafana_user/tasks/main.yml
CI currently fails on devel because Python 3.8 is no more supported.
The errors on devels can be ignored.
Ref: #264
> test(team-and-user): add tests with encoded char in login/name

- changelogs/fragments/add-units-datasource.yml
- plugins/modules/grafana_datasource.py
- tests/unit/modules/grafana/grafana_datasource/test_grafana_datasource.py
Adding these tests aims at being capable to detect drifts in the sent
requests when one is refoactoring the module.
Add unit tests to cover `grafana_datasource` module.
grafana_datasource.py
Adding these tests aims at being able to split `get_datasource_payload` function is several functions (one per datasource type) to ease readability and maintenance.
> test(datasource): Add unit tests for grafana_datasource module

- .github/workflows/ansible-test.yml
- changelogs/fragments/ci.yml
This patch is based on @webknjaz work on https://github.com/ansible-collections/community.grafana/pull/266 but only applies changes to the sanity and units tests stages.
Integration tests will continue using the current method to benefit from the matrix usage combined with the Github service feature to start Grafana.
> ci(actions): use ansible-test github action for sanity and units

- .github/workflows/ansible-test.yml
- README.md
- changelogs/fragments/fix-263.yaml
- plugins/modules/grafana_datasource.py
- tests/integration/targets/grafana_datasource/tasks/elastic.yml
- tests/sanity/ignore-2.15.txt
In latest versions of Grafana, the elastic version is no more provided as an integer even if it is still supported and won't return any error.
To ease configuration, the module will accept the version format as displayed by the WUI (ex: "7.10+") and will map the value to what the API expects ("7.10.0").
The added values are the one supported by Grafana 8 and 9 (greater than elastic 7.0 which was already supported).
The module will keep on supporting the old format to avoid a breaking change with significant impact.
The integer format could be dropped when Grafana 10 would be released since the versions we support would be 8.x to 10.x that will all support the new format.
Fixes: #263
`grafana_datasource`
> Add support for more elasticsearch version as datasource

- .github/workflows/ansible-test.yml
- changelogs/fragments/270-gha--ansible-test--integration.yml
Supersedes
https://github.com/ansible-collections/community.grafana/pull/266.
This patch replaces manually maintained copy-paste of `ansible-test`
invocations with the use of a reusable GitHub Action[[1]] that wraps
it allowing to only keep the matrix on the project side allowing the
reusable bits to be maintained separately and be shared across the
community.
This has been earlier implemented for the `community.digitalocean`
collection[[2]] and some tests in this collection[[3]] among others.
The feature allowing `ansible-test` access service containers has
been implemented in v1.9.0 version of the action[[4]].
Resolves https://github.com/ansible-collections/community.grafana/pull/266
[1]: https://github.com/ansible-community/ansible-test-gh-action
[2]: …
> Use ansible-test-gh-action GHA @ integration tests

- changelogs/fragments/191.yml
- plugins/modules/grafana_dashboard.py
No method of reproduction was found/provided for #191, as a prevention
measure this patch specifies the encoding to use when opening a file to
avoid the open function to auto determine the preferred encoding based
on the locale.
Closes: #191
`grafana_dashboard`
> fix(dashboard): specify utf-8 as encoding when opening files

- .github/workflows/ansible-test.yml
- changelogs/fragments/277-gha-ansible-test-versions.yml
Update GitHub Actions matrix to test with last version of Ansible (and drop old ones).
Fixes: #277
> Update matrix to drop ansible 2.11 & 2.12 and add 2.14

- changelogs/fragments/288_get_actual_org_encode.yml
- plugins/modules/grafana_organization.py
Fixed the issue when creating an org with spaces in it's name.
you would get the following error:
`Cannot connect to API Grafana An unknown error occurred: URL can't contain control characters. \"/api/orgs/name/'Test Org space'\" (found at least ' ')`
grafana_organization module
```paste below
Having spaces in the org name might not be for everyone, but it is allowed by grafana it self.
```
> get_actual_org url encode fix

- galaxy.yml
Correct collection URLs in galaxy.yml
- The repository name is ansible-collections/community.grafana not ansible-collections/grafana
- Point to the Ansible docsite for documentation
galaxy.yml
> Correct collection URLs in galaxy.yml

- changelogs/fragments/300_datasource_prometheus_time_interval.yml
- plugins/modules/grafana_datasource.py
Add `time_interval` option for `prometheus` datasources as it helps to handle scrape frequency.
module: grafana_datasource
```paste below
```
> Datasource prometheus time interval

- hacking/requirements.txt
I bumped requests library 2.28.2 to 2.31.0, because my environment dependabot alert to requests 2.28.2.
I understood this code is part of CI and this has no effect.
But this is annoying warning for users with dependabot enabled.
this is just suggestion, if this project decide to don't care it, please just close this PR.
https://github.com/advisories/GHSA-j8r2-6x86-q33q
> Bump requests from 2.28.2 to 2.31.0

- changelogs/fragments/fix-316.yml
- plugins/modules/grafana_datasource.py
If there is no check for its presence, this will fail if a datasource is not configured with basic auth at all. In that case it would try to remove an entry from the dict that is not there resulting in a KeyError.
When comparing the existing datasource with the should be state, basicAuth is handled incorrectly in the case when the datasource is not configured with basicAuth at all. This case would result in a KeyError which this change fixes.
grafana_datasource.py
See also https://github.com/ansible-collections/community.grafana/issues/248
> Fix KeyError when comparing datasource without basicAuth

- changelogs/fragments/318-org_users_by_org_name.yml
- plugins/modules/grafana_organization_user.py
- tests/integration/targets/grafana_organization_user/tasks/main.yml
- (Bugfix Pull Request)
**module**: grafana_organization_user
This PR adds the ability to manage organization users by `org_name`, not just `org_id`.
... and a small bugfix to check if user is already in organization.
```paste below
```
> feat(organization_user): manage users by org_name

- changelogs/fragments/321-action-groups-org-users.yml
- meta/runtime.yml
`grafana_organization_user` was missing in `action_groups.grafana`
**module:** grafana_organization_user
```paste below
```
> fix: add grafana_organization_user to action_group grafana

- README.md
Added a section to the README mentioning the [telekom-mms.grafana](https://github.com/telekom-mms/ansible-role-grafana) collection.
**docs:** README
```paste below
```
> docs: complementary collection `telekom-mms.grafana`

- changelogs/fragments/325_true_false.yml
- plugins/callback/grafana_annotations.py
- plugins/doc_fragments/basic_auth.py
- plugins/modules/grafana_dashboard.py
- plugins/modules/grafana_datasource.py
- plugins/modules/grafana_folder.py
- plugins/modules/grafana_notification_channel.py
- plugins/modules/grafana_plugin.py
- plugins/modules/grafana_team.py
fixes #301 
```paste below
```
> default to true/false

- changelogs/fragments/335-add-datasource-type-tempo.yml
- plugins/modules/grafana_datasource.py
- tests/integration/targets/grafana_datasource/tasks/tempo.yml
Add support for Grafana Tempo datasource
datasource
Tempo is distributed tracing backend developed by Grafana Labs
https://grafana.com/docs/grafana/latest/datasources/tempo/
> Add tempo datasource support

- .gitignore
- changelogs/fragments/324_formatting.yml
- hacking/find_grafana_versions.py
- plugins/callback/grafana_annotations.py
- plugins/doc_fragments/api_key.py
- plugins/doc_fragments/basic_auth.py
- plugins/lookup/grafana_dashboard.py
- plugins/module_utils/base.py
- plugins/modules/grafana_dashboard.py
- plugins/modules/grafana_datasource.py
- plugins/modules/grafana_folder.py
- plugins/modules/grafana_notification_channel.py
- plugins/modules/grafana_organization.py
- plugins/modules/grafana_organization_user.py
- plugins/modules/grafana_plugin.py
- plugins/modules/grafana_team.py
- plugins/modules/grafana_user.py
- tests/requirements.yml
- tests/unit/modules/grafana/grafana_datasource/test_grafana_datasource.py
- tests/unit/modules/grafana/grafana_plugin/test_grafana_plugin.py
- tests/unit/modules/grafana/grafana_team/test_grafana_team.py
- tests/unit/modules/grafana/grafana_user/test_grafana_user.py
- Format with black
- remove unused variables
t
```paste below
```
> Formatting

- changelogs/fragments/332-datasource-by-org-name.yml
- plugins/modules/grafana_datasource.py
Like https://github.com/ansible-collections/community.grafana/pull/318 and https://github.com/ansible-collections/community.grafana/pull/331, but for `grafana_datasource` :)
Instead of specifying `org_id`, you can use `org_name`...
**module:** grafana_datasource
```paste below
```
> feat(datasource): manage datasources by org_name

- changelogs/fragments/238_checkmode.yml
- tests/integration/targets/grafana_dashboard/runme.sh
- tests/integration/targets/grafana_dashboard/site.yml
- tests/integration/targets/grafana_datasource/runme.sh
- tests/integration/targets/grafana_datasource/site.yml
- tests/integration/targets/grafana_folder/runme.sh
- tests/integration/targets/grafana_folder/site.yml
- tests/integration/targets/grafana_folder/tasks/main.yml
- tests/integration/targets/grafana_notification_channel/runme.sh
- tests/integration/targets/grafana_notification_channel/site.yml
- tests/integration/targets/grafana_organization/runme.sh
- tests/integration/targets/grafana_organization/site.yml
- tests/integration/targets/grafana_organization/tasks/main.yml
- tests/integration/targets/grafana_organization_user/runme.sh
- tests/integration/targets/grafana_organization_user/site.yml
- tests/integration/targets/grafana_organization_user/tasks/main.yml
- tests/integration/targets/grafana_team/runme.sh
- tests/integration/targets/grafana_team/site.yml
- tests/integration/targets/grafana_team/tasks/main.yml
- tests/integration/targets/grafana_user/runme.sh
- tests/integration/targets/grafana_user/site.yml
- tests/integration/targets/grafana_user/tasks/main.yml
when a runme.sh exists in the test-path, it will be run. then the roles will be run in check-mode and normal-mode to test if they work in check mode (at least somewhat)
> try run tests in check-mode, too

- changelogs/fragments/308_datasource_quickwit.yml
- plugins/modules/grafana_datasource.py
- tests/integration/targets/grafana_datasource/tasks/quickwit.yml
Add support Quickwit datasource
datasource
https://github.com/quickwit-oss/quickwit-datasource
Example usage
```paste below
- name: Create Quickwit datasource
community.grafana.grafana_datasource::
name: "Quickwit"
grafana_url: "{{ grafana_url }}"
grafana_user: "{{ grafana_username }}"
grafana_password: "{{ grafana_password }}"
access: proxy
org_id: '1'
ds_type: quickwit-quickwit-datasource
ds_url: http://localhost:7280/api/v1
additional_json_data:
index: 'hdfs-logs'
timeField: timestamp
timeOutputFormat: unix_timestamp_secs
logMessageField: body
logLevelField: severity_text
```
> add Quickwit datasource

- .github/workflows/lint.yml
- README.md
- changelogs/fragments/341-lint-ruff.yml
Fixes #337 
Related #339 
- github workflow
```paste below
```
> ci: workflow python ruff linting

- changelogs/fragments/345-datasource-compare-diff-orgid.yml
- plugins/modules/grafana_datasource.py
If `org_name` is set instead of `org_id`, comparing the diff (after/before) to determine whether something has changed or not does not work.
- module `grafana_datasource`
```json
"diff": {
"after": {
"access": "proxy",
"basicAuth": false,
"database": "",
"isDefault": false,
"jsonData": {
"tlsAuth": false,
"tlsAuthWithCACert": false
},
"name": "Loki",
"orgId": 1, # <-- datasource left unchanged in orgId 6 but diff uses default value of org_id (1) to compare so it's "changed"
"type": "loki",
"url": "http://loki-stack-loki-stack:3100",
"user": "",
"withCredentials": false
},
"before": {
"access": "proxy",
"basicAuth": false,
"database": "",
"isDefault": false,
"jsonData": {
"tlsAuth": false,
"tlsAuthWithCACert": false
},
"name": "Loki",
"orgId": 6,
"type": "loki", …
```
> fix(grafana_datasource): orgId by name if defined to compare diff

- changelogs/fragments/350-python3.12.yml
- tests/unit/modules/grafana/grafana_team/test_grafana_team.py
- tests/unit/modules/grafana/grafana_user/test_grafana_user.py
`TestCase.assertEquals` is depracated and removed in Python 3.12.
test
> test: replace deprecated TestCase.assertEquals

- CHANGELOG.rst
- changelogs/changelog.yaml
- galaxy.yml
- new release 1.8.0
```paste below
```
> build(1.8.0): release version

- changelogs/fragments/353-docs-add-influxdb-flux-example.yml
- plugins/modules/grafana_datasource.py
I've added an example to grafana_datasource to add the flux version of influxdb programatically. It's very hard to find documentation online, especially for people new to ansible (and grafana).
> docs(grafana_datasource): add influxdb flux example

- changelogs/fragments/355-rm-dashboard-message-argument.yml
- plugins/modules/grafana_dashboard.py
remove `message` argument from `grafana_dashboard` to fix sanity test workflow
```paste below
```
> fix(grafana_dashboard): remove message argument

- changelogs/fragments/354-fix-find-grafana-versions.yml
- hacking/check_fragment.sh
- hacking/find_grafana_versions.py
- tests/sanity/ignore-2.15.txt
- tests/sanity/ignore-2.16.txt
- tests/unit/modules/grafana/grafana_plugin/test_grafana_plugin.py
- increase number of returned releases by api to ensure the newest 3 majors are included
- refactor comparation of version numbers
- work with multi digits major versions
- compare versions as tulpe not as int
- before: `10.0.13 (as_int: 10013) > 10.2.6 (as_int: 1026)` (older version is higher)
- after: `10.0.13 (as_tulpe: (10, 0, 13)) < 10.2.6 (as_tulpe: (10, 2, 6))` (newer version is higher)
before:
```
["9.5.18", "10.0.13"]
```
after:
```
["8.5.27", "9.5.18", "10.4.1"]
```
> ci: fix get latest grafana versions python script

- changelogs/fragments/356-lookup-dashboards-add-custom-certs-verification-logic.yml
- plugins/lookup/grafana_dashboard.py
This fix adds the `validate_certs`, `ca_path` options to the lookup plugin. Both parameters comply with the `get_url` functionality of ansible-core and provides additional utility to perform lookup of dashboards from Grafana instances that are configured with Self-Signed Certificates.
`validate_certs` option value defaults to `true` - following the pattern of `url` lookup plugin from the Core.
`ca_path` option value is set explicitly when using the plugin else defaults to `None`.
Fixes #346
Lookup Plugin for Grafana Dashboards
Tested with a Grafana Docker image with Self-Signed Certificates as well as a local Certificate Authority. The Local CA along with a self-signed certificate is used to form a `chain.crt` and validated as `ca_path` option for the plugin.
> fix(lookup/grafana_dashboard): add custom certs verification logic

- changelogs/fragments/376-dashboard-lookup-api-key-deprecation.yml
- plugins/lookup/grafana_dashboard.py
removed check and handling of mangled api key (deprecated for 2.0.0) #375 
```paste below
```
> fix(grafana_dashboard): removed check and handling of mangled api key

- changelogs/fragments/378-grafana-version-sorting.yml
- hacking/find_grafana_versions.py
#377 reveals an error in the version sorting, so that grafana 11.0.0 is not one of the 3 current major versions
```paste below
❯ python hacking/find_grafana_versions.py
["11.0.0", "10.4.4", "9.5.19"]
```
> fix: grafana version sorting

- changelogs/fragments/382-notification-channel-deprecation.yml
- meta/runtime.yml
- plugins/modules/grafana_notification_channel.py
- tests/integration/targets/grafana_notification_channel/tasks/main.yml
- Fixes integration test workflows for Grafana v11 coming with #377
- Deprecate module `grafana_notification_channel` (legacy alerting removed with Grafana v11)
```paste below
```
> fix(grafana_notification_channel): deprecation

- changelogs/fragments/396-datasource-diff-apiversion.yml
- plugins/modules/grafana_datasource.py
Remove the apiVersion field from the return of the current datasource so that the comparison of the current and the new datasource works.
```paste below
```
> fix(grafana_datasource): remove field apiVersion from return of current datasource

- changelogs/fragments/395-datasource-tls-servername.yml
- plugins/modules/grafana_datasource.py
Fixes #389 
```paste below
```
> feat(grafana_datasource): add tls_servername argument

- changelogs/fragments/287-alertmanager-datasource.yml
- plugins/modules/grafana_datasource.py
- tests/integration/targets/grafana_datasource/tasks/alertmanager.yml
- tests/integration/targets/grafana_datasource/tasks/main.yml
This adds the "alertmanager" datasource. [Apparently added in Grafana 9.2.](https://grafana.com/docs/grafana/latest/whatsnew/whats-new-in-v9-2/#configure-external-alertmanagers-as-data-sources)
grafana_datasource plugin
> Support alertmanager Grafana datasource

- changelogs/fragments/406-python3.12.yml
- tests/unit/modules/grafana/grafana_silence/test_grafana_silence.py
`TestCase.assertEquals` was deprecated and removed in Python 3.12.
Similar to #350, but for code that was added later.
test
> test: replace more deprecated assertEquals

- changelogs/fragments/416-dashboard-uid.yml
- plugins/modules/grafana_dashboard.py
- tests/integration/targets/grafana_dashboard/tasks/dashboard-from-id.yml
The "uid" module parameter wasn't send to the API and new dashboard was created instead instead of updated. 
This patch fixes it by copying uid from data to the payload
grafana_dashboard.py
> grafana_dashboard: copy uid from data to payload

- changelogs/fragments/411-dashboard-subfolders.yml
- plugins/modules/grafana_dashboard.py
- roles/grafana/README.md
- roles/grafana/tasks/main.yml
- tests/integration/targets/grafana_dashboard/site.yml
- tests/integration/targets/grafana_dashboard/tasks/dashboard-folder-destination.yml
Since Grafana 11, it is possible to have dashboards in subfolders. This enables users to manage dashboards in those.
Fixes #410
Fixes #388 
I am not quite sure how to increase the code coverage there, as, as far as I can tell, this is tested through the integration tests. Is that a problem? If so, any pointers?
> Allow managing dashboards in subfolders

- changelogs/fragments/428-dashboard-change-detection.yml
- plugins/modules/grafana_dashboard.py
- tests/integration/targets/grafana_dashboard/tasks/dashboard-folder-destination.yml
For recent versions of grafana, change detection for dashboards in folders is broken. This is because the `folderId` in the API response from grafana is now in the `meta` section, not the `dashboard` section:
https://grafana.com/docs/grafana/latest/developers/http_api/dashboard/#get-dashboard-by-uid
This patch changes the behaviour of `is_grafana_dashboard_changed()` to look up the `folderId` from the `meta` section (if it exists) and copy it to the `dashboard` section so that the `if payload == dashboard` check will pass for dashboards in folders that don't have the default `folderId` of 0.
There is an included integration test which works against this patch, but fails against the main branch.
You can use a local ansible playbook to reproduce the …
> fix(grafana_dashboard): fix change detection for dashboards in folders
