ansible-collections/community.grafana

LICENSE
README.md

GPLv3 Licence file

---

.github/settings.yml
LICENSE

Work around for Settings Bot not honoring //github.com/gundalow-collection/.github/blob/master/.github/settings.yml

Hack settingsBot

---

.github/settings.yml

(Hopefully) allow non-Admins to commit

---

.github/workflows/ansible-test.yml
tests/coverage.sh

Code coverage support for unit and integration tests. 

Codecoverage

---

README.md

Add Code Coverage badge

---

README.md

Add a badge showing CI status on master.

Add a badge providing CI status on master

---

galaxy.yml

Updating `galaxy.yml` to allow v0.1.0 release to be built.
galaxy.yml

Update galaxy.yml for 0.1.0 release

---

plugins/modules/grafana_datasource.py
tests/integration/targets/grafana_datasource/tasks/main.yml
tests/integration/targets/grafana_datasource/tasks/thruk.yml

Add Thruk as a Grafana Datasource
Updates the grafana_datasource module
Replaces the following commands:
```bash
grafana-cli plugins install sni-thruk-datasource
```
This will install this datasource plugin: https://grafana.com/plugins/sni-thruk-datasource

Add Thruk as Grafana Datasource

---

tests/integration/targets/grafana_datasource/tasks/thruk.yml

The GitHub Actions were not triggered on the pull request from a fork and I missed the [sanity tests issues](https://github.com/ansible-collections/grafana/commit/458f1977ba0db496b1088a7755e3f67410945e23/checks?check_suite_id=377427157) when I merged the patch.

Fixing sanity tests errors detected on master

---

plugins/modules/grafana_user.py
tests/integration/targets/grafana_user/defaults/main.yml
tests/integration/targets/grafana_user/meta/main.yml
tests/integration/targets/grafana_user/tasks/main.yml
tests/unit/modules/grafana/grafana_user/test_grafana_user.py

Add a module to manage (create, update, delete) Grafana user
- grafana_user.py
Sponsored by @rrey

Manage Grafana User

---

plugins/modules/grafana_folder.py
plugins/modules/grafana_team.py
tests/integration/targets/grafana_folder/defaults/main.yml
tests/integration/targets/grafana_folder/meta/main.yml
tests/integration/targets/grafana_folder/tasks/main.yml

Add Grafana_folder module.
grafana_folder.py

Add grafana_folder module with integration tests

---

.github/workflows/ansible-test.yml

ansible-minimal has been archived, so use ansible-base

CI: Use ansible-base

---

codecov.yml

Avoid a reducing coverage diff from failing CI

Avoid codecov failing if diff drops

---

plugins/doc_fragments/api_key.py
plugins/doc_fragments/basic_auth.py
plugins/modules/grafana_dashboard.py
plugins/modules/grafana_folder.py
plugins/modules/grafana_team.py
plugins/modules/grafana_user.py

The `grafana-user` module was not using the doc fragment and grafana_argument-spec
grafana_user.py

Use module_utils doc fragment and argument_spec in grafana_user

---

plugins/modules/grafana_dashboard.py
plugins/modules/grafana_datasource.py
plugins/modules/grafana_plugin.py
tests/sanity/ignore-2.10.txt

* Added datatypes
* Fixed documentation
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>
plugins/modules/grafana_dashboard.py
plugins/modules/grafana_datasource.py
plugins/modules/grafana_plugin.py
tests/sanity/ignore-2.10.txt

Fix grafana modules documentation

---

README.md

Document the supported versions of Grafana.
In parallel I have created this issue : https://github.com/grafana/grafana/issues/22388
Closes: #21

Add a mention in README about the supported versions of Grafana

---

plugins/modules/grafana_plugin.py
tests/sanity/ignore-2.10.txt
tests/sanity/ignore-2.9.txt
tests/unit/modules/grafana/grafana_plugin/test_grafana_plugin.py

Adding very minimal tests that covers issues reported on `grafana_plugin` during plugin version parsing.

Add unit tests for grafana_plugin

---

galaxy.yml

Release 0.2.0

---

README.md

Fix bad links and ref to Kubernetes

---

plugins/callback/grafana_annotations.py
plugins/lookup/grafana_dashboard.py
plugins/modules/grafana_datasource.py
plugins/modules/grafana_folder.py
plugins/modules/grafana_plugin.py
plugins/modules/grafana_team.py

Fix linter warnings

---

.all-contributorsrc
README.md

Reverts ansible-collections/grafana#63

Revert "docs: add jpmens as a contributor"

---

plugins/modules/grafana_datasource.py

Fixes: #67
Reproduced issue and validated fix with following playbook:
```paste below
- hosts: localhost
collections:
- community.grafana
vars:
grafana_url: "http://127.0.0.1:3000"
grafana_admin_user: "admin"
grafana_admin_password: "admin"
grafana_datasources: []
grafana_datasource_tls_skip_verify: true
grafana_datasource_with_credentials: true
grafana_datasources:
- name: "icinga2-influxdb"
database: "icinga2"
ds_type: "influxdb"
password: "icinga2"
url: "https://127.0.0.1:8086"
user: "icinga2"
tasks:
- community.grafana.grafana_datasource:
name: "{{ item.name }}"
access: "{{ item.access | default(omit) }}"
basic_auth_password: "{{ item.basic_auth_password | default(omit) }}"
basic_auth_user: "{{ item.basic_auth_user | default(omit) }}" …
```

Fix test on attributes presence in the datasource

---

plugins/callback/grafana_annotations.py
plugins/lookup/grafana_dashboard.py
tests/sanity/ignore-2.9.txt

I saw differences in the DOCUMENTATION string in some module but it isn't raising anything in the sanity tests.
Also fixed the sanity errors that were reported about ignores that are no more required.
Closes: #66

Port ansible-collection-migration diff

---

CHANGELOG.md
galaxy.yml

Update galaxy.yml to release v0.2.1

Release v0.2.1

---

.github/workflows/ansible-test.yml

CI should use devel

---

plugins/modules/grafana_folder.py

Do URL encoding/quote
Decode to utf-8 for compare of existing folder.
Fix: #78
grafana_folder

Support special chars in folder name fix #78

---

plugins/modules/grafana_datasource.py
tests/integration/targets/grafana_datasource/tasks/cloudwatch.yml
tests/integration/targets/grafana_datasource/tasks/elastic.yml
tests/integration/targets/grafana_datasource/tasks/influx.yml
tests/integration/targets/grafana_datasource/tasks/main.yml
tests/integration/targets/grafana_datasource/tasks/postgres.yml
tests/integration/targets/grafana_datasource/tasks/thruk.yml

Refactor `grafana_datasource` using a class handling the interface with grafana API

Refactor grafana_datasource

---

plugins/modules/grafana_dashboard.py

When testing dashboad payload between the test resulted in reverted values
leading to the dashboard not being updated when it should.
Closes: #76

dashboard: fix issue during import

---

plugins/modules/grafana_dashboard.py

as mentioned in #77 @rrey 
Need to remove payload meta key for compare. Otherwise dashboard will be changed (always) 

remove meta key if exists for compare

---

CHANGELOG.md
galaxy.yml

Update galaxy.yml and Changelog

Release 0.2.2

---

plugins/modules/grafana_datasource.py
tests/integration/targets/grafana_dashboard/tasks/dashboard-from-file.yml
tests/integration/targets/grafana_dashboard/tasks/dashboard-from-id.yml
tests/integration/targets/grafana_dashboard/tasks/dashboard-from-url.yml
tests/integration/targets/grafana_dashboard/tasks/delete-dashboard.yml
tests/integration/targets/grafana_datasource/tasks/loki.yml
tests/integration/targets/grafana_datasource/tasks/main.yml
tests/integration/targets/grafana_team/tasks/create_user.yml
tests/integration/targets/grafana_user/tasks/main.yml

This PR adds support for Loki datasources including tests.
Fixes #92 
While I was testing I noticed that not all test used the variables defined in the defaults.
I added this in a separate commit, but if you like I can also open a second PR for this.

Support for Loki Datasource

---

plugins/modules/grafana_dashboard.py

Fixing error reported in sanity brought for free by ansible upstream without notice :(

Fix sanity tests

---

.github/workflows/rebase.yml
tests/sanity/ignore-2.11.txt

Update reabse action

---

plugins/modules/grafana_datasource.py
tests/integration/targets/grafana_datasource/tasks/main.yml
tests/integration/targets/grafana_datasource/tasks/zabbix.yml

There wasn't any option to include user and password for Zabbix API
(They are different fields to _Basic Auth_ username and password)

Zabbix user and password

---

plugins/modules/grafana_datasource.py
tests/integration/targets/grafana_datasource/tasks/postgres.yml

see #101 
```paste below
- name: Create postgres datasource
grafana_datasource:
name: "datasource-postgres"
grafana_url: "https://grafana.company.com"
grafana_user: "admin"
grafana_password: "xxxxxx"
org_id: "1"
ds_type: "postgres"
ds_url: "postgres.company.com:5432"
database: "db"
user: "postgres"
password: "iampgroot"
sslmode: "verify-full"
additional_json_data:
timescaledb: false
```

adding additional_json_data param

---

plugins/modules/grafana_dashboard.py
plugins/modules/grafana_folder.py
plugins/modules/grafana_plugin.py
plugins/modules/grafana_team.py
plugins/modules/grafana_user.py
tests/unit/modules/grafana/grafana_plugin/test_grafana_plugin.py

fix #103
also added tests
grafana_plugin

check cmd result on uninstall

---

.github/workflows/ansible-test.yml
README.md

Test the collection against the 3 latest major.minor versions.

Update Grafana versions used by CI

---

README.md
changelogs/fragments/1.0.0.yml

Update Changelog for 1.0.0

---

CHANGELOG.rst
README.md
changelogs/changelog.yaml
changelogs/fragments/1.0.0.yml

Fixing changelog that was not proprly re-built

Fix changelog

---

.github/workflows/ansible-test.yml
meta/runtime.yml
tests/integration/targets/grafana_datasource/tasks/elastic.yml

Add a matrix variable for Ansible version supported (starting at 2.9).
Closes: #132

Update ci to test against fixed Ansible version

---

plugins/modules/grafana_notification_channel.py
tests/integration/targets/grafana_notification_channel/defaults/main.yml
tests/integration/targets/grafana_notification_channel/tasks/dingding.yml
tests/integration/targets/grafana_notification_channel/tasks/discord.yml
tests/integration/targets/grafana_notification_channel/tasks/email.yml
tests/integration/targets/grafana_notification_channel/tasks/googlechat.yml
tests/integration/targets/grafana_notification_channel/tasks/hipchat.yml
tests/integration/targets/grafana_notification_channel/tasks/kafka.yml
tests/integration/targets/grafana_notification_channel/tasks/line.yml
tests/integration/targets/grafana_notification_channel/tasks/main.yml
tests/integration/targets/grafana_notification_channel/tasks/opsgenie.yml
tests/integration/targets/grafana_notification_channel/tasks/pagerduty.yml
tests/integration/targets/grafana_notification_channel/tasks/prometheus.yml
tests/integration/targets/grafana_notification_channel/tasks/pushover.yml
tests/integration/targets/grafana_notification_channel/tasks/sensu.yml
tests/integration/targets/grafana_notification_channel/tasks/slack-and-beyond.yml
tests/integration/targets/grafana_notification_channel/tasks/teams.yml
tests/integration/targets/grafana_notification_channel/tasks/telegram.yml
tests/integration/targets/grafana_notification_channel/tasks/threema.yml
tests/integration/targets/grafana_notification_channel/tasks/victorops.yml
tests/integration/targets/grafana_notification_channel/tasks/webhook.yml

This adds initial notification channels support.
There's number of TODOs to fix, add the secure settings support  introduced in 7.2, better documentation, probably something else.
I only tested it well with slack, integration tests check only the fact that all types of channels are created and removed, probably there can be issues with type-specific parameters. 
Fixes #137

Add initial notification channels support

---

plugins/modules/grafana_datasource.py

Minor update on documentation to setup the PostgreSQL datasource version
`grafana_datasource`
Say hi to "The tech guy" for me 👋

docs: setting postgres version in example

---

plugins/module_utils/base.py
plugins/modules/grafana_dashboard.py
plugins/modules/grafana_datasource.py

Fixes: `UnboundLocalError: local variable 'folder_exists' referenced before assignment`
Closes: #146

Fix UnboundLocalError in grafana_dashboard.py

---

changelogs/fragments/1.2.0.yml
galaxy.yml
plugins/modules/grafana_datasource.py
plugins/modules/grafana_folder.py
plugins/modules/grafana_team.py
plugins/modules/grafana_user.py

Return a comprehensive error message when failing at retrieving the version from /api/health
Ref: #147

grafana_folder: Add a parameter to skip version check

---

tests/sanity/ignore-2.11.txt
tests/sanity/ignore-2.12.txt

https://github.com/ansible-collections/overview/issues/45#issuecomment-813821100

Add ignore.txt for 2.11 and 2.12

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/1.2.1.yml
galaxy.yml

v1.2.1
======
Bugfixes
--------
- Fix issue with grafana_user that failed to create admin user (#142)

Release v1.2.1

---

README.md

This adds some missing README links and updates the others to point to the new place where the collection documentation lives
README
N/A
```

Update some readme links

---

.github/workflows/ansible-test.yml
changelogs/fragments/1.2.2.yml
plugins/modules/grafana_datasource.py
plugins/modules/grafana_folder.py
plugins/modules/grafana_team.py
plugins/modules/grafana_user.py
tests/integration/targets/grafana_user/tasks/main.yml

Remove `uid` returned since Grafana 8.x from datasource diff. 
Fixes #176
`grafana_datasource`

Fix uid datasource

---

.github/workflows/ansible-test.yml

See if this installs `ssh-keygen`

WIP install test requirement

---

changelogs/fragments/192-add-module-grafana_organization.yml
plugins/modules/grafana_organization.py
tests/integration/targets/grafana_organization/defaults/main.yml
tests/integration/targets/grafana_organization/tasks/main.yml

Create/delete organization in API Grafana
grafana_organization
grafana_organization
none

grafana_organization

---

changelogs/fragments/fix_slashes_in_datasources.yml
plugins/modules/grafana_datasource.py
tests/integration/targets/grafana_datasource/tasks/elastic.yml
tests/integration/targets/grafana_datasource/tasks/issues.yml

WIP: Remove '/' as a safe char from datasource name quote function call

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/192-add-module-grafana_organization.yml
galaxy.yml

build(release): 1.3.0

---

.github/workflows/ansible-test.yml
changelogs/fragments/notifi_channel_refacto.yml
plugins/modules/grafana_notification_channel.py
tests/integration/targets/grafana_notification_channel/tasks/dingding.yml
tests/integration/targets/grafana_notification_channel/tasks/discord.yml
tests/integration/targets/grafana_notification_channel/tasks/email.yml
tests/integration/targets/grafana_notification_channel/tasks/googlechat.yml
tests/integration/targets/grafana_notification_channel/tasks/hipchat.yml
tests/integration/targets/grafana_notification_channel/tasks/kafka.yml
tests/integration/targets/grafana_notification_channel/tasks/line.yml
tests/integration/targets/grafana_notification_channel/tasks/main.yml
tests/integration/targets/grafana_notification_channel/tasks/opsgenie.yml
tests/integration/targets/grafana_notification_channel/tasks/pagerduty.yml
tests/integration/targets/grafana_notification_channel/tasks/prometheus.yml
tests/integration/targets/grafana_notification_channel/tasks/pushover.yml
tests/integration/targets/grafana_notification_channel/tasks/sensu.yml
tests/integration/targets/grafana_notification_channel/tasks/slack-and-beyond.yml
tests/integration/targets/grafana_notification_channel/tasks/teams.yml
tests/integration/targets/grafana_notification_channel/tasks/telegram.yml
tests/integration/targets/grafana_notification_channel/tasks/threema.yml
tests/integration/targets/grafana_notification_channel/tasks/victorops.yml
tests/integration/targets/grafana_notification_channel/tasks/webhook.yml

The grafana_notification_channel integration tests did not include idempotency tests.
This patch adds idempotency tests and refactors the code with Class based implementation that will allow to factorize in `module_utils` in the future.
Refs: #189 
grafana_notification_channel

grafana_notification_channel: add idempotency tests and refactor to ease maintenance.

---

changelogs/fragments/grafana_users_note.yaml
plugins/modules/grafana_user.py

docs(grafana_user): Added a note about `grafana_api_key` being unsupported

---

README.md

Add missing modules to readme
grafana_notification_channel & grafana_organization
grafana_notification_channel
grafana_organization

Add missing modules to readme

---

tests/sanity/ignore-2.14.txt

Relates to https://github.com/ansible-collections/news-for-maintainers/issues/13

Copy ignore-2.13.txt to ignore-2.14.txt

---

.github/workflows/ansible-test.yml

Relates to https://github.com/ansible-collections/news-for-maintainers/issues/14

add stable-2.13 in test matrix

---

changelogs/fragments/172_support_azure_datasource.yml
plugins/modules/grafana_datasource.py
tests/integration/targets/grafana_datasource/tasks/azure.yml
tests/integration/targets/grafana_datasource/tasks/main.yml

Support azure datasource
fix #172 

Support azure datasource

---

changelogs/fragments/248_ds_update_error_grafana_9.yml
plugins/modules/grafana_datasource.py

Fix grafana_datasource issue with Grafana >=9.0.0

---

changelogs/fragments/257_pretty_printed_dashboard_export.yml
plugins/modules/grafana_dashboard.py
tests/integration/targets/grafana_dashboard/tasks/dashboard-export.yml
tests/integration/targets/grafana_dashboard/tasks/main.yml

Export dashboard with pretty printed JSON.
Fixes: #257

feat: export dashboard with pretty printed JSON

---

.github/workflows/ansible-test.yml
CHANGELOG.rst
changelogs/changelog.yaml
galaxy.yml
hacking/check_fragment.sh

Release v1.5.1

---

.github/CODEOWNERS

You folks know what you are doing, you don't need my reviews.
On an related topic, it's great to see that the GitHub Action you've put in place continues to allow you to test new versoins of Grafana easily, ie https://github.com/ansible-collections/community.grafana/pull/294

CODEOWNERS: Reduce review requirements

---

changelogs/fragments/285_fix_doc.yml

Add changelog fragment for #285

docs(galaxy): fix url for docs.ansible.com

---

plugins/modules/grafana_dashboard.py

Fix typo in grafana_dashboard module documentation
grafana_dashboard module

Fix typo in grafana_dashboard module documentation

---

.github/workflows/lint.yml
changelogs/fragments/339-lint-black.yml
plugins/callback/grafana_annotations.py
plugins/doc_fragments/api_key.py
plugins/doc_fragments/basic_auth.py
plugins/lookup/grafana_dashboard.py
plugins/modules/grafana_dashboard.py
plugins/modules/grafana_folder.py
plugins/modules/grafana_team.py

#337 
- github workflows
```paste below
```

ci: workflow python black linting

---

CHANGELOG.rst
changelogs/changelog.yaml
galaxy.yml

- new release v1.7.0
```paste below
```

build(1.7.0): release version

---

changelogs/fragments/add grafana_silence module.yml
meta/runtime.yml
plugins/modules/grafana_silence.py
tests/integration/targets/grafana_silence/defaults/main.yml
tests/integration/targets/grafana_silence/runme.sh
tests/integration/targets/grafana_silence/site.yml
tests/integration/targets/grafana_silence/tasks/main.yml
tests/unit/modules/grafana/grafana_silence/test_grafana_silence.py

This PR adds the grafana_silence module, that is used to schedule, delete and manage silences.
- grafana_silence
```paste below
```

feat: add grafana_silence module

---

.github/workflows/ansible-test.yml
changelogs/fragments/368-molecule-pin-requests.yml

https://github.com/psf/requests/issues/6707
```paste below
```

fix(molecule): pin requests version <2.32.0

---

changelogs/fragments/367-dashboard-undo-breaing-change-message.yml
plugins/modules/grafana_dashboard.py
tests/sanity/ignore-2.15.txt
tests/sanity/ignore-2.16.txt
tests/sanity/ignore-2.18.txt

fix(grafana_dashboard): undo breaking change remove of message argument

---

CHANGELOG.rst
changelogs/changelog.yaml
galaxy.yml

Fixes #367 
- release
```paste below
```

build(1.9.1): release version

---

changelogs/fragments/372-rm-dashboard-message-argument.yml
plugins/modules/grafana_dashboard.py
tests/sanity/ignore-2.15.txt
tests/sanity/ignore-2.16.txt
tests/sanity/ignore-2.17.txt
tests/sanity/ignore-2.18.txt

replica of #355 because of #367 (#368)
```paste below
```

fix(grafana_dashboard): remove message argument

---

changelogs/fragments/374-ansible-required-version.yml
meta/runtime.yml
roles/grafana/meta/main.yml

bump required ansible version to 2.15.0
```paste below
```

fix: bump required ansible version to 2.15.0

---

CHANGELOG.rst
changelogs/changelog.yaml
galaxy.yml
plugins/modules/grafana_contact_point.py
plugins/modules/grafana_silence.py

new release 2.0.0
```paste below
```

build(2.0.0): release version

---

changelogs/fragments/379-contact-points-org-name-func-args.yml
plugins/modules/grafana_contact_point.py

add missing func arg
```paste below
```

fix(grafana_contact_point): org handling func args

---

changelogs/fragments/392-dashboard-lookup-apikey.yml
plugins/lookup/grafana_dashboard.py

fix(grafana_dashboard): lookup - check if api key is defined

---

changelogs/fragments/397-improve-datasource-tests.yml
tests/integration/targets/grafana_datasource/site.yml
tests/integration/targets/grafana_datasource/tasks/alertmanager.yml
tests/integration/targets/grafana_datasource/tasks/azure.yml
tests/integration/targets/grafana_datasource/tasks/cloudwatch.yml
tests/integration/targets/grafana_datasource/tasks/elastic.yml
tests/integration/targets/grafana_datasource/tasks/errors.yml
tests/integration/targets/grafana_datasource/tasks/influx.yml
tests/integration/targets/grafana_datasource/tasks/issues.yml
tests/integration/targets/grafana_datasource/tasks/loki.yml
tests/integration/targets/grafana_datasource/tasks/main.yml
tests/integration/targets/grafana_datasource/tasks/postgres.yml
tests/integration/targets/grafana_datasource/tasks/quickwit.yml
tests/integration/targets/grafana_datasource/tasks/redis.yml
tests/integration/targets/grafana_datasource/tasks/tempo.yml
tests/integration/targets/grafana_datasource/tasks/thruk.yml
tests/integration/targets/grafana_datasource/tasks/uid.yml
tests/integration/targets/grafana_datasource/tasks/zabbix.yml

Move some grafana auth args from task to playbook level.
- Test improvements
```paste below
```

test(grafana_datasource): improve tests

---

.github/workflows/check_grafana_releases.yml
changelogs/fragments/421-grafana-workflow.yml

Some GitHub Action versions bumps and little adjustions to the actions and workflow permission.
Closes #422 
```paste below
```

ci: bump action versions and adjust permissions and trigger

---

CHANGELOG.rst
changelogs/changelog.yaml
galaxy.yml

New release v2.2.0
- Release
```paste below
```

build(2.2.0): release version
